server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=effi_record
    username: postgres
    password: admin
  flyway:
    enabled: true
    schemas: effi_record
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    validate-on-migrate: true
    baselineOnMigrate: true
    logging: debug

  jpa:
    properties:
      hibernate:
        default_schema: effi_record
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

effirecord:
  openapi:
    dev-url: http://localhost:${server.port}/api/v1
    prod-url: http://localhost:${server.port}/api/v1